require('config.settings')
require('config.autocmd')
require('config.plugins')
require('config.keymapping')
require('setup.cmp')
require('setup.treesitter')
require('setup.feline')
require('setup.session_manager')
require('setup.nvim_tree')
-- require('setup.onedark')
require('setup.bufferline')
-- require('setup.mason')
-- require('setup.lspconfig')

require('config.custom')
