vim.api.nvim_set_keymap('n', '<S-h>', '<cmd>bprevious<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<S-l>', '<cmd>bNext<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<S-c>', '<cmd>bdelete<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-h>', '<Left>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-j>', '<Down>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-k>', '<Up>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-Space>', '<ESC>', { noremap = true, silent = true})
